import type {Metadata} from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Link from "next/link";
import {Inter} from "next/font/google";

const runy = localFont({src: '../fonts/RunyTunesRevisitedNF.otf'})
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <meta
                name="description"
                content="The official website for New Age Animations."
            />
            <title>New Age Animations</title>
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/site.webmanifest"/>
            <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
            <meta name="msapplication-TileColor" content="#da532c"/>
            <meta name="theme-color" content="#ffffff"/>

            <meta name="keywords"
                  content="animations,newageanimations, new age animations, na animations, naa, 3d animations, 3d characters, tanzania animations, newage, animations,new age, new, age "/>
            <meta property="og:title" content="New Age Animations" data-rh="true"/>
            <meta property="og:description" content="The official website for New Age Animations." data-rh="true"/>
            <meta property="og:image" content="/naa.png" data-rh="true"/>
        </head>
        <body className={` ${inter.className} h-auto gradient w-screen overflow-x-hidden `}>
        <header className={` ${runy.className} absolute w-screen top-0 left-0`}>
            <nav className="w-full z-30 backdrop-blur-sm flex justify-between fixed top-0 left-0 px-4 md:px-10">
                <div className="my-6">
                    <Link href={"/"}>
                <span className="font-runy uppercase text-2xl tracking-widest text-shadow">
                  NAA
                </span>
                    </Link>
                </div>
                <div className="flex justify-evenly">
                    {/* <Link to={"/about"}>
                <div className="capitalize pt-7 text-gray-400 hover:text-green-900 duration-100 pr-4">
                  about
                </div>
              </Link> */}
                    {/* <Link to={"/videos"}>
                <button className="rounded-3xl duration-100 border-2 border-green-200  capitalize my-4 px-4 py-2 bg-green-200 font-bold hover:border-green-900 text-green-900">
                  animations
                </button>
              </Link> */}
                </div>
            </nav>
        </header>

        {children}
        <footer className="fixed  text-gray-400 z-20 bottom-0 left-0 w-full flex justify-between  md:px-10 p-4">
            <div>Animation Studio</div>
            <div>newageanimations &copy; </div>
        </footer>
        </body>
        </html>
    )
        ;
}
