import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";

const runy = localFont({ src: '../fonts/RunyTunesRevisitedNF.otf' })
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={` ${inter.className} h-auto gradient w-screen overflow-x-hidden `}>
    <header className={` ${runy.className} absolute w-screen top-0 left-0`}>
      <nav className="w-full z-30 backdrop-blur-sm flex justify-between fixed top-0 left-0 px-4 md:px-10">
        <div className="my-6">
          <Link href={"/"}>
                <span className="font-runy uppercase text-2xl tracking-widest text-shadow">
                  NAA
                </span>
          </Link>
        </div>
        <div className="flex justify-evenly">
          {/* <Link to={"/about"}>
                <div className="capitalize pt-7 text-gray-400 hover:text-green-900 duration-100 pr-4">
                  about
                </div>
              </Link> */}
          {/* <Link to={"/videos"}>
                <button className="rounded-3xl duration-100 border-2 border-green-200  capitalize my-4 px-4 py-2 bg-green-200 font-bold hover:border-green-900 text-green-900">
                  animations
                </button>
              </Link> */}
        </div>
      </nav>
    </header>

    {children}
    <footer className="fixed  text-gray-400 z-20 bottom-0 left-0 w-full flex justify-between  md:px-10 p-4">
      <div>Animation Studio</div>
      <div>newageanimations &copy; </div>
    </footer>
    </body>
    </html>
  )
    ;
}
